### ISSUE TITLE
Add timezone name aliases

### ISSUE THREAD

**Issue by fadedmax** [Voxel-Fox-Ltd/Apple.Py#106]
for example; `.tz set est` or `.tz set mst` or `.tz set gmt`

**Comment by 4Kaylum** [comment]
This can be achieved with the `pytz` module. On a related note, storing location would be much preferable to just storing offsets as I do now, because that would deal with DST better than it does now (meaning: at all).

**Comment by sn8to** [comment]
DST could be potentially separated into its own setting, as some regions don't participate while literally everyone else surrounding them does. Other than adding logic for that, it'd make sense to at least have some sort of override in that scenario. I do +1 the idea of adding DST in general though.

**Comment by 4Kaylum** [comment]
Much the same as #111 if we store things in the same way they're given (`etc`, `mst`, etc). Closing that to get attention here.

**Comment by 4Kaylum** [comment]
Closed with 97b403901e7d11cdf9702813a0beaba86c82ca17, 1131a6e01fc9ae1a6429c755693dc08ce1514c3f, and d695d472004de35027de61db1a54eda7bfc49fa6.
