### ISSUE TITLE
add `tzp get` (time zone period get)

### ISSUE THREAD

**Issue by ghost** [Voxel-Fox-Ltd/Apple.Py#107]
it basically either returns midnight, morning, evening, afternoon, or noon

**Comment by 4Kaylum** [comment]
Do you have issue reading the times in `tz get`?

**Comment by ghost** [comment]
> Do you have issue reading the times in `tz get`?

Most of the time when I'm using `tz get` it's to check if it's morning or night or noon or afternoon or midnight for the person

**Comment by 4Kaylum** [comment]
What justifies adding it as its own command rather than just something in parentheses in the `tz get` command?

**Comment by ghost** [comment]
> What justifies adding it as its own command rather than just something in parentheses in the `tz get` command?

More detail please

**Comment by 4Kaylum** [comment]
What detail do you need? I'm asking why you want to add it as its own command rather than an extension of what's already there.

**Comment by ghost** [comment]
> What detail do you need? I'm asking why you want to add it as its own command rather than an extension of what's already there.

When I say I'm checking for the period of time, it means I'm trying to do at a glance, I don't wanna have to sift through a bunch of other content to get what I want

**Comment by 4Kaylum** [comment]
Other content being a few words? I'm not sure the difference between `The current time for @Kae is estimated to be **1:01 AM**.` and `The current time for @Kae is estimated to be **1:01 AM**. It is the **night**.` would be too much for you.

**Comment by ghost** [comment]
> Other content being a few words? I'm not sure the difference between `The current time for @Kae is estimated to be **1:01 AM**.` and `The current time for @Kae is estimated to be **1:01 AM**. It is the **night**.` would be too much for you.

Are you saying this would be easy for the users or easy for you to implement?

**Comment by ghost** [comment]
> > Other content being a few words? I'm not sure the difference between `The current time for @Kae is estimated to be **1:01 AM**.` and `The current time for @Kae is estimated to be **1:01 AM**. It is the **night**.` would be too much for you.
> 
> Are you saying this would be easy for the users or easy for you to implement?

(not meant as an attack I just realized it sounds like it sorry)

**Comment by 4Kaylum** [comment]
I'm asking why you want it as a new command rather than an addition to what you have currently.

**Comment by ghost** [comment]
> I'm asking why you want it as a new command rather than an addition to what you have currently.

It can be included in the current command, but I'd like a new command that just specifies the time period for when I don't have that much time to check but really wanna check

**Comment by 4Kaylum** [comment]
I don't see the value in a command that does nothing unique when an existing command shows exactly the same data.

**Comment by ghost** [comment]
> I don't see the value in a command that does nothing unique when an existing command shows exactly the same data.

Then you choose if you want it in a separate command or in the same command, I'm not gonna argue anymore because I don't wanna disrespect you

**Comment by 4Kaylum** [comment]
PR it into the current command and I'll merge it.

**Comment by 4Kaylum** [comment]
Chris has now left the server and I'm not interested in adding this myself.
