### ISSUE TITLE
You can't add images to issues (without copying the url and such)

### ISSUE THREAD

**Issue by fadedmax** [Voxel-Fox-Ltd/Apple.Py#130]
low priority but meh

**Comment by 4Kaylum** [comment]
This doesn't work if we want to keep the image - when you delete a message the attachments _on_ the image get removed from Discord's fileserver. What do?

**Comment by SpicyTakis** [comment]
This may sound bootleg but, if the command contains a image, you can just post it to another channel then use that link?

**Comment by 4Kaylum** [comment]
That's sketch. I'd rather not repost/rehost the content anywhere tbh.

**Comment by sn8to** [comment]
What about uploading to the GitHub CDN like what happens when you drag an image file to the comment box?

**Comment by 4Kaylum** [comment]
> What about uploading to the GitHub CDN like what happens when you drag an image file to the comment box?

I _think_ that's just a caching system, but I'll look into it as a solution. I'd rather Github host it than I do. That solution doesn't work for Gitlab, though.

**Comment by irismessage** [comment]
Gitlab lets you drag images I believe

**Comment by 4Kaylum** [comment]
The simple solution would be to not have the bot delete the message if there's an attachment to it, but that doesn't really stop the user deleting the message themselves.

As far as I can tell, Github's "upload image" API isn't public/documented. I've not checked for Gitlab's as of yet.

**Comment by 4Kaylum** [comment]
Dumb idea: can I give a base64 string as an image? What's the character limit in git comments?

![Test](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4///w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)

Edit: apparently not.

**Comment by Silverdimond** [comment]
I believe the gitlab's "upload a file" API (https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/projects.md#upload-a-file) is what you are looking for on gitlab but github does not have a public api for this

**Comment by 4Kaylum** [comment]
I'd prefer a universal issue. What if I have the bot just DM the image back to the user, and then use the URL for _that_ attachment? It wouldn't work with certain filesizes, but that's not really an issue for _images_ of all things.

**Comment by Silverdimond** [comment]
Isn't that the same thing that SpicyTakis suggested?

**Comment by 4Kaylum** [comment]
I read their suggestion more as copying any sent files to a private channel in a server, but I guess it is the same concept.

**Comment by 4Kaylum** [comment]
Does this work?

![unknown.png](https://cdn.discordapp.com/attachments/211227365764890626/821181538388541440/unknown.png)

**Comment by 4Kaylum** [comment]
It does!
