### ISSUE TITLE
add a checker for valid github URLS when using gh/foo/bar

### ISSUE THREAD

**Issue by ghost** [Voxel-Fox-Ltd/Apple.Py#159]
https://discord.com/channels/208895639164026880/636085718002958336/826474518964076624

**Comment by 4Kaylum** [comment]
* Doing this is a web request where it doesn't need to be
* This will fail if a repo is private
* Does this really matter?

**Comment by ghost** [comment]
> * Doing this is a web request where it doesn't need to be
> * This will fail if a repo is private
> * Does this really matter?

yes, it matters, doing the bare minimum just because you want to isn't the way to go

**Comment by 4Kaylum** [comment]
You haven't answered the other two points.
I feel this doesn't matter as the syntax of `gh/aaa/bbb` is explicit enough that it doesn't trigger on anything else - people are running it with these arguments deliberately.

**Comment by ghost** [comment]
> You haven't answered the other two points.
> I feel this doesn't matter as the syntax of `gh/aaa/bbb` is explicit enough that it doesn't trigger on anything else - people are running it with these arguments deliberately.

someone could be using random words or letters to make the bot respond with a link that would flood the chat

**Comment by 4Kaylum** [comment]
So your suggestion instead is to flood Github with API requests?

**Comment by irismessage** [comment]
> 
> 
> > You haven't answered the other two points.
> > I feel this doesn't matter as the syntax of `gh/aaa/bbb` is explicit enough that it doesn't trigger on anything else - people are running it with these arguments deliberately.
> 
> someone could be using random words or letters to make the bot respond with a link that would flood the chat

You realise there's already a `ping` command, right?

**Comment by ghost** [comment]
> > > You haven't answered the other two points.
> > > I feel this doesn't matter as the syntax of `gh/aaa/bbb` is explicit enough that it doesn't trigger on anything else - people are running it with these arguments deliberately.
> > 
> > 
> > someone could be using random words or letters to make the bot respond with a link that would flood the chat
> 
> You realise there's already a `ping` command, right?

for what

**Comment by irismessage** [comment]
Not to mention literally any other command the bot replies to

**Comment by ghost** [comment]
> > * This will fail if a repo is private
there could be a subommand: gh/foo/bar/private

**Comment by 4Kaylum** [comment]
That changes the syntax for no reason.

**Comment by 4Kaylum** [comment]
And even if it _did_ help, then your original point is moot ANYWAY, because then people can just tack `/private` to the end of what they're saying.

**Comment by ghost** [comment]
> And even if it _did_ help, then your original point is moot ANYWAY, because then people can just tack `/private` to the end of what they're saying.

don't you have apple.py linked to people's github accounts though? check the API via their account to see if it's a valid private repo

**Comment by ghost** [comment]
https://applepy.voxelfox.co.uk/

**Comment by 4Kaylum** [comment]
> 
> 
> > And even if it _did_ help, then your original point is moot ANYWAY, because then people can just tack `/private` to the end of what they're saying.
> 
> don't you have apple.py linked to people's github accounts though? check the API via their account to see if it's a valid private repo

I don't see a need to use people's Oauth info to check if a repository exists. I'm happy with the system as is now.

**Comment by 4Kaylum** [comment]
Was there a reason you opened this? Did you see this being abused somewhere?

**Comment by ghost** [comment]
I opened it because it's unnecessary to allow invalid bot requests
