### ISSUE TITLE
add charparse

### ISSUE THREAD

**Issue by ghost** [Voxel-Fox-Ltd/Apple.Py#160]
.charparse %40 = `@`

**Comment by 4Kaylum** [comment]
What do you want this command to do? Where is a reference for what `%40` is?

**Comment by ghost** [comment]
> What do you want this command to do? Where is a reference for what `%40` is?

%40 is @

**Comment by ghost** [comment]
according to .charinfo, anyways

**Comment by 4Kaylum** [comment]
According to what

**Comment by ghost** [comment]
\U00000040: COMMERCIAL AT - @ — http://www.fileformat.info/info/unicode/char/40

**Comment by 4Kaylum** [comment]
Here's a list of valid encodings for the `@` symbol. What do you suggest we use as a reference, and why do you feel it needs to be a command? I don't see many people trying to ask the bot "hello what is u200b".

![Screen Shot 2021-03-31 at 16 46 58](https://user-images.githubusercontent.com/5342536/113017669-9ca31000-9177-11eb-8bf4-062d5b798aba.png)

**Comment by ghost** [comment]
from urllib.parse import unquote

url = unquote(url)


------------

from urllib import unquote

url = unquote(url).decode('utf8')

**Comment by 4Kaylum** [comment]
Oh, cool. If you wanna PR that in, go right ahead. I've no interest in adding it myself nor do I see any real demand for it, so I'm closing the issue.
