### ISSUE TITLE
add electron docs to rtfm

### ISSUE THREAD

**Issue by sn8to** [Voxel-Fox-Ltd/Apple.Py#161]
https://www.electronjs.org/docs/all

**Comment by Silverdimond** [comment]
![picture of 404](https://media.discordapp.net/attachments/751246248102592567/828038509494534205/html.png?width=993&height=559) am i doing something wrong or why is it 404'ing

**Comment by 4Kaylum** [comment]
`curl 'https://bh4d9od16a-dsn.algolia.net/1/indexes/*/queries' --data-raw '{"requests":[{"indexName":"electronjs","params":"query=clipboard&hitsPerPage=5"}]}'`

This works if you use an API key - I can't work out where you sign up for one though.

**Comment by 4Kaylum** [comment]
After looking some more I'm not sure I actually _can_ sign up for one, so I'm closing this.
