### ISSUE TITLE
update to daylight savings timezones

### ISSUE THREAD

**Issue by ghost** [Voxel-Fox-Ltd/Apple.Py#163]
should be 9:52 https://discord.com/channels/208895639164026880/636085718002958336/827042775559176223

**Comment by ghost** [comment]
or maybe make a command that switches between daylight savings references

example: `.tz daylight_savings on` (can be user-specific command (only reference daylight savings for whoever wants it) or a bot-owner-only command(reference for everyone in America timezones)

**Comment by 4Kaylum** [comment]
This was solved by using locations instead of times.
