### ISSUE TITLE
add pull requests short form (e.g. !123)

### ISSUE THREAD

**Issue by sn8to** [Voxel-Fox-Ltd/Apple.Py#177]
uhh yeah do it

**Comment by fadedmax** [comment]
@GlitchMasta47 Is there a discord thread about this? How do you want this to work?

E.G

m!88
to
https://github.com/Voxel-Fox-Ltd/MarriageBot/pull/88

Something like that?

**Comment by 4Kaylum** [comment]
This exists as a hashtag format, but I'll alias in the `!` too.
