### ISSUE TITLE
Add blacklist for animal names

### ISSUE THREAD

**Issue by fadedmax** [Voxel-Fox-Ltd/Apple.Py#185]
The api can return some weird animal names, so a blacklist for them would be nice based on some weird ones

**Comment by irismessage** [comment]
Do you have any examples

**Comment by fadedmax** [comment]
Some guy got named "Asian Giant Hornet", but yeah i still think it'd be a easy to add feature, just connect it to a db, add bot support checks and such (similar to the topic add?)

**Comment by irismessage** [comment]
What's wrong with asian giant hornets

**Comment by 4Kaylum** [comment]
I'm not interested in adding this - I don't see a need for it.

**Comment by irismessage** [comment]
I find it strange that you think 'asian giant hornet' is somehow offensive but not 'blacklist'

**Comment by fadedmax** [comment]
fair. i think that some of them are just outright weird. maybe i'm an idiot, who knows.

**Comment by Silverdimond** [comment]
I agree, some animal names can be strange.
