### ISSUE TITLE
.avatar: Command raised an exception: UnboundLocalError: local variable 'url' referenced before assignment

### ISSUE THREAD

**Issue by irismessage** [Voxel-Fox-Ltd/Apple.Py#190]
https://discord.com/channels/714154158969716780/714154159590473801/838732962082193438

**Comment by 4Kaylum** [comment]
![image](https://user-images.githubusercontent.com/5342536/116882963-f5554500-ac1c-11eb-8b76-efb0a82359a7.png)

:kaepensive:

**Comment by irismessage** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/5342536/116882963-f5554500-ac1c-11eb-8b76-efb0a82359a7.png)
> 
> :kaepensive:

it's cmpc server you left when you elft a bunch of things

https://cmpc.live/discord

**Comment by 4Kaylum** [comment]
That just makes this a bad bug report smh
