### ISSUE TITLE
Google image stop button should recognize server moderators and delete all reactions accordingly, as if they were the author of the message.

### ISSUE THREAD

**Issue by fadedmax** [Voxel-Fox-Ltd/Apple.Py#197]

**Comment by 4Kaylum** [comment]
just delete the message lmao

**Comment by 4Kaylum** [comment]
More seriously: it just uses the vbu paginator and I don't really care for adding moderator override functions to that. 

If you want the reactions removed, clear the reactions on the message. It won't stop users adding more reactions themselves, but who really cares for that. 

The request you opened this issue for is functionality that I don't plan to add.
