### ISSUE TITLE
Resize image makes image smaller, to allow for discord emoji file size limit

### ISSUE THREAD

**Issue by fadedmax** [Voxel-Fox-Ltd/Apple.Py#207]
(bibi messages are unrelated)

![unknown.png](https://cdn.discordapp.com/attachments/785651028908572685/852633501589438484/unknown.png)

**Comment by 4Kaylum** [comment]
this feature is already present. do you have an example that isn't working?

**Comment by Silverdimond** [comment]
![image](https://user-images.githubusercontent.com/46320280/121602800-1db83680-ca48-11eb-9c3f-d06ae1789977.png)
Idk if max was mistaken or something but this clearly is not the stealemoji command failing for file size
