### ISSUE TITLE
Fix the 'components' being referenced before assignment for .google search

### ISSUE THREAD

**Issue by iHeroGH** [Voxel-Fox-Ltd/Apple.Py#214]
https://discord.com/channels/208895639164026880/208895639164026880/873056231475011674

**Comment by 4Kaylum** [comment]
Bad mobile screenshot I'm fairly certain is relevant

![Screenshot_20210806-052354_Termius.jpg](https://user-images.githubusercontent.com/5342536/128455774-2c3be94b-d380-4b64-92d2-cc82dcd93db3.jpg)

**Comment by iHeroGH** [comment]
This is an issue with VBU's paginator - https://github.com/Voxel-Fox-Ltd/VoxelBotUtils/pull/124

**Comment by 4Kaylum** [comment]
This will be fixed when Apy updates to VBU version 0.6 (after its release).
