### ISSUE TITLE
.timezone commands don’t take 24h time

### ISSUE THREAD

**Issue by fadedmax** [Voxel-Fox-Ltd/Apple.Py#43]
like the bcc, dig dig dig it it

actual stuff:
bot doesn’t like 24h for .tz set commands, that would be nice, there are other people besides america lol

**Comment by 4Kaylum** [comment]
If you look in the code you can see that it absolutely does accept 24 hour time. I set my own timezone using 24 hour time, as did you. I'm not in America myself, Max. You know this. Could you screenshot your issue?
