### ISSUE TITLE
don't allow the same message to be quoted multiple times

### ISSUE THREAD

**Issue by sn8to** [Voxel-Fox-Ltd/Apple.Py#72]
prevents spam or accidental double quotes

**Comment by 4Kaylum** [comment]
How would I go about doing this? I had a check for this when I was storing message content, but with how it works now I'm unable to check a quote content without checking every message that the user has quoted, which is a GET request per message.

**Comment by sn8to** [comment]
maybe don't store message content, maybe just check the stored message id to make sure a single message isn't quoted multiple times

**Comment by 4Kaylum** [comment]
The message ID that's stored is the ID of the posted message (ie the one that goes into your quotes channel). The ID of the original message isn't stored. This also isn't an easy thing to patch in, since the original quote message could be _multiple_ messages, as Apy supports that.

**Comment by 4Kaylum** [comment]
Ultimately I don't think this is possible.
