### ISSUE TITLE
`editissue` command

### ISSUE THREAD

**Issue by sn8to** [Voxel-Fox-Ltd/Apple.Py#73]
edit an existing issue
- usage: `.editissue Author/Repo#123`
- responds with menu where you can edit title or body, or add a new comment

**Comment by 4Kaylum** [comment]
Kindof an aside, but should I group these commands? `issue create whatever`, `issue edit whatever`, `issue close whatever`? What do you think?

**Comment by sn8to** [comment]
Sounds good and works well with the slash commands system.

**Comment by 4Kaylum** [comment]
Reference for later development: https://docs.github.com/en/rest/reference/issues#update-an-issue
This command could also be used to close the issue in question by updating its state attribute to `closed`.
