### ISSUE TITLE
New issue commands

### ISSUE THREAD

**Issue by 4Kaylum** [Voxel-Fox-Ltd/Apple.Py#82]
Opening this so I can group #73 and #74.

- [x] `issue comment` command to add comments to an issue
- [ ] `issue edit` command to edit an issue (low priority)
- [x] `issue close` command to close an issue - this could merge with edit as it's the same endpoint
- [x] `issue list` command to list issues on a repo
- [x] Change `createissue` command to `issue create` (possibly keeping `ci` as an alias)

These commands could use the same git repo templates as already exist (`gh/user/repo` or the inbuilt aliases), though this would make more sense to add as a converter for the future.

Issues should be given as an int which we don't need to validate, since we can just give a generic "I couldn't comment/edit that issue" etc.

Here's the relevant API docs: 
* Github - https://docs.github.com/en/rest/reference/issues#update-an-issue
* Gitlab https://docs.gitlab.com/ee/api/issues.html#edit-issue

Pinging the original issue openers: @GlitchMasta47 @SpicyTakis

**Comment by sn8to** [comment]
`issue open` should also be included, either separate or combined into `issue edit`.

**Comment by 4Kaylum** [comment]
My guy
![image](https://user-images.githubusercontent.com/5342536/108911617-65dd5580-761f-11eb-8bc9-95650094e093.png)

**Comment by 4Kaylum** [comment]
Issue list command is now added, though it needs pagination.

**Comment by 4Kaylum** [comment]
Thinking about it, I could probably include `issue assign [repo] [issueid] @user` for users who have linked accounts. Is that something of interest?

**Comment by sn8to** [comment]
> My guy
> ![image](https://user-images.githubusercontent.com/5342536/108911617-65dd5580-761f-11eb-8bc9-95650094e093.png)

oops I meant to say `issue open`

**Comment by 4Kaylum** [comment]
> > My guy
> > ![image](https://user-images.githubusercontent.com/5342536/108911617-65dd5580-761f-11eb-8bc9-95650094e093.png)
>
> oops I meant to say `issue open`

Is this the same as `issue create` (added as an alias), or do you want a command to re-open a closed issue?

**Comment by sn8to** [comment]
It could be either but I was thinking about reopening closed issues.

**Comment by 4Kaylum** [comment]
I'm not sure there's much need for reopening issues from Discord. I already filter out closed issues from the `issue list` command; do you think it's something you'd use a lot of?

**Comment by sn8to** [comment]
It could be an alias and `issue close` can stay to toggle between open/closed states.

**Comment by 4Kaylum** [comment]
Issue #92 is related to this stuff - mentioning it here because I can.

**Comment by 4Kaylum** [comment]
Test comment from the Apy integration.

**Comment by 4Kaylum** [comment]
Test comment from the Apy integration number 2.

**Comment by 4Kaylum** [comment]
That completes the `issue comment` command.

**Comment by 4Kaylum** [comment]
`issue close` completed with #94.

**Comment by 4Kaylum** [comment]
With the `issue edit` command: how should we approach this? Issues are composed of comments, and editing an individual comment would be a pain. What should we do? @GlitchMasta47 @JMcB17 @SpicyTakis

**Comment by SpicyTakis** [comment]
Maybe edit the users last comment?

**Comment by sn8to** [comment]
I was originally thinking about `issue edit` editing the original issue. I could only think of comment editing working by either showing users a list of comments available and letting them choose one, or letting them pass the comment url (which is dumb because to get it they'd have to be on the page anyways and they might as well click the edit button instead of the copy link button).

**Comment by 4Kaylum** [comment]
> I was originally thinking about `issue edit` editing the original issue. I could only think of comment editing working by either showing users a list of comments available and letting them choose one, or letting them pass the comment url (which is dumb because to get it they'd have to be on the page anyways and they might as well click the edit button instead of the copy link button).

I was originally thinking about editing the original issue as well but I'm not sure that really matters after at least one comment has been left.

**Comment by sn8to** [comment]
> Maybe edit the users last comment?

Editing the most recent comment made by the user sounds good since I can't think of any other reasons to edit comments that aren't the most recent.

**Comment by 4Kaylum** [comment]
I think that based on it not being immediately obvious what it does: I shouldn't add it as a command. Opinions?

**Comment by 4Kaylum** [comment]
After some thinking I'm genuinely not sure that `issue edit` is worth developing. Please someone change my mind if you feel strongly about this.

**Comment by irismessage** [comment]
We could model some functionality off the GitHub cli tool: https://cli.github.com/manual
For `issue edit` my opinion would be that it should edit the original body.

**Comment by irismessage** [comment]
The cli tool doesn't have this though:
```
C:\Users\joelm>gh issue -h
Work with GitHub issues

USAGE
  gh issue <command> [flags]

CORE COMMANDS
  close:      Close issue
  comment:    Create a new issue comment
  create:     Create a new issue
  list:       List and filter issues in this repository
  reopen:     Reopen issue
  status:     Show status of relevant issues
  view:       View an issue
```
I might tend to agree about dropping the edit command.

**Comment by 4Kaylum** [comment]
I've already added close, comment, create, and list (although list isn't paginated). I'm not sure anything else is really WANTED as a Discord integration. 

Our last discussion was on assign, but that still needs thought.

**Comment by 4Kaylum** [comment]
Concept: I use the Github activity API endpoints to send you a DM when you get a new notification on git. 
https://docs.github.com/en/rest/reference/activity#notifications

It doesn't look like I can get the same system on Gitlab; the closest I can find is the todo list API.
https://docs.gitlab.com/ee/api/todos.html
Feel free to point me in the right direction if you find something more viable.

Thoughts?

**Comment by sn8to** [comment]
I like the idea, it sounds pretty interesting, however I use email notifications since they're default and I don't have to do any setup.

**Comment by aikocc** [comment]
> 
> 
> Concept: I use the Github activity API endpoints to send you a DM when you get a new notification on git.
> https://docs.github.com/en/rest/reference/activity#notifications
> 
> It doesn't look like I can get the same system on Gitlab; the closest I can find is the todo list API.
> https://docs.gitlab.com/ee/api/todos.html
> Feel free to point me in the right direction if you find something more viable.
> 
> Thoughts?

I quite like that!

**Comment by 4Kaylum** [comment]
Thoughts for that workflow:

* Get user notifications (since last poll)
* For each notification
    * Check reason
    * See if the reason is different from the last polled reason (this will either need to be cached or databased, and if it's our first poll what should we do here?)
    * If so, send special notification (issue closed, assigned, etc)
    * Otherwise the notification is a new comment - [grab its content and author](https://docs.github.com/en/rest/reference/issues#get-an-issue-comment) and send that back

I think I'll need to test this to see how it works. The reason field is slightly confusing to me, honestly.

**Comment by 4Kaylum** [comment]
I've decided against that flow for the time being. I'll add `issue assign` and then close this. I'm happy with how these commands have been added.

**Comment by 4Kaylum** [comment]
After Max saying to many times I have now abandoned `issue assign`. That concludes this issue.
