### ISSUE TITLE
Allow issue body to be modified again while creating issue

### ISSUE THREAD

**Issue by sn8to** [Voxel-Fox-Ltd/Apple.Py#92]
e.g. you make a typo in the original body, you can't go back and change the body without going to github and editing the issue because the ➕ was removed

**Comment by 4Kaylum** [comment]
Best I'm willing to do is replace message body rather than modify. That alright?

**Comment by sn8to** [comment]
Yeah I meant replace, e.g. ask them again for the new body.

**Comment by 4Kaylum** [comment]
Coolio that's fine.
