### ISSUE TITLE
Change meow chat "you can't say that" text for moderators

### ISSUE THREAD

**Issue by 4Kaylum** [Voxel-Fox-Ltd/Apple.Py#97]
If the user whose message is being deleted has the relevant permission, tell them how they're able to _turn off_ meow chat.

**Comment by fadedmax** [comment]
Can i be assigned this issue? also: what perms should the user need?

**Comment by 4Kaylum** [comment]
The same permission that `meow off` needs - you can check the command for that. I don't mind about it being dynamic, just hardcode it in.
