### ISSUE TITLE
add a ci for bots that don't have repos

### ISSUE THREAD

**Issue by ghost** [Voxel-Fox-Ltd/Apple.Py#98]
setting up github/gitlab is a hassle, and not always needed

**Comment by 4Kaylum** [comment]
The `ci` command opens an issue on a git repo. How do you propose opening an issue on a repo that doesn't exist?

**Comment by ghost** [comment]
> The `ci` command opens an issue on a git repo. How do you propose opening an issue on a repo that doesn't exist?

If it gives an error for the repo not existing, then create an entry in a database with the issue specified, with the bot's user ID as the primary key

**Comment by 4Kaylum** [comment]
I would rather not have to deal with this kind of thing myself, `ci` and `issue` + its subcommands are specifically meant for interacting with Gitlab and Github. I'm not greatly interested in databasing this myself.
