### ISSUE TITLE
repo links should default to GitHub if not specified

### ISSUE THREAD

**Issue by irismessage** [Voxel-Fox-Ltd/Apple.Py#99]
e.g. thesilvercraft/SilverBot would be the same as gh/thesilvercraft/SilverBot

**Comment by fadedmax** [comment]
personally i'm against this, might cause conflicts with gitlab, and it's 3 characters, plus most people who use this usally have repo aliases(i'd be happy to make one for you), this is a bit biased but /shrug

**Comment by 4Kaylum** [comment]
People use slashes in regular language. This wouldn't make sense to add - to the git link regex anyway. For the commands I'm not so sure, but I'd rather keep it consistent between the two.
